sudo: false
language: node_js
node_js:
- '8.10.0'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: false
before_script:
- npm run clean
script:
- npm run tsc
- npm run lint
- npm run export
- npm run pre-deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./out
  on:
    branch: master
